name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: mundo-precisa-pai-prod
  REGION: us-central1
  SERVICE_NAME: frontend-web
  REGISTRY: us-central1-docker.pkg.dev
  REPO: containers   # nome do repo criado no Artifact Registry

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: sistemas/web/package-lock.json
      - name: Install dependencies
        run: |
          cd sistemas/web
          npm ci
      - name: Run tests
        run: |
          cd sistemas/web
          ./test-ci.sh
      - name: Run linting
        run: |
          cd sistemas/web
          npm run lint
      - name: Build application
        run: |
          cd sistemas/web
          npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: sistemas/web/package-lock.json

      - name: Install dependencies
        run: |
          cd sistemas/web
          npm ci

      - name: Build application
        run: |
          cd sistemas/web
          npm run build
        env:
          REACT_APP_VERSION: ${{ github.sha }}
          REACT_APP_BUILD_DATE: ${{ github.event.head_commit.timestamp }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build and push Docker image
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_NAME }}
        run: |
          cd sistemas/web
          docker build -t $IMAGE:${{ github.sha }} .
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Deploy to Cloud Run
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_NAME }}
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars "NODE_ENV=production" \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 10 \
            --min-instances 0 \
            --port 80

      - name: Get service URL
        run: |
          echo "Service URL: $(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format='value(status.url)')"

      - name: Notify deployment
        run: |
          echo "🚀 Deployment completed successfully!"
